replicaCount: 1

image:
  repository: myjenkinsacr.azurecr.io/demo-app
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: demo-app.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

autoscaling:
  enabled: false

resources: {}
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
volumeMounts: []
volumes: []

serviceAccount:
  create: false
  name: ""
